# Switch prefix to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Split the pane using | and -
bind | split-window -h
bind - split-window -v

# Move the pane using the arrow keys without needing a prefix.
set -g mouse on

# Reload config with prefix + r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Window/pane numbers start from 1
set -g base-index 1
setw -g pane-base-index 1
